"use client";
import { useEffect,useState } from "react";
import { ClipboardList, Plus, Search, Upload, Truck } from "lucide-react";
import { api } from "@/lib/api";
type Supplier={id:string;name:string;code:string};
type Product={id:string;sku:string;name_ar:string;default_cost:number};
type Location={id:string;name:string;code:string};
type Line={product:Product;quantity:number;unit_cost:number;conversion_factor:number};
export default function Purchases(){
 const [suppliers,setSuppliers]=useState<Supplier[]>([]),[products,setProducts]=useState<Product[]>([]),[locations,setLocations]=useState<Location[]>([]),[supplier,setSupplier]=useState<Supplier|null>(null),[location,setLocation]=useState<Location|null>(null),[lines,setLines]=useState<Line[]>([]),[q,setQ]=useState(""),[msg,setMsg]=useState(""),[invoiceNo,setInvoiceNo]=useState(""),[discount,setDiscount]=useState(""),[tax,setTax]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{api<Supplier[]>("/suppliers").then(setSuppliers).catch(()=>{});api<Product[]>("/products").then(setProducts).catch(()=>{});api<Location[]>("/locations").then(x=>{setLocations(x);setLocation(x[0]||null)}).catch(()=>{})},[]);
 const add=(p:Product)=>{setLines(x=>x.some(v=>v.product.id===p.id)?x.map(v=>v.product.id===p.id?{...v,quantity:v.quantity+1}:v):[...x,{product:p,quantity:1,unit_cost:Number(p.default_cost||0)}]);setQ("")};
 const subtotal=lines.reduce((s,l)=>s+l.quantity*l.unit_cost,0); const total=Math.max(0,subtotal-Number(discount||0)+Number(tax||0));
 const post=async()=>{if(!supplier||!location||!lines.length)return setMsg("اختار المورد والموقع وأضف الأصناف.");setSaving(true);setMsg("");try{const r=await api<{document_number:string}>("/purchases",{method:"POST",body:JSON.stringify({supplier_id:supplier.id,location_id:location.id,supplier_invoice_number:invoiceNo||undefined,discount:Number(discount||0),tax:Number(tax||0),idempotency_key:crypto.randomUUID(),items:lines.map(l=>({product_id:l.product.id,quantity:l.quantity,conversion_factor:l.conversion_factor,unit_cost:l.unit_cost}))})});setMsg(`تم استلام ${r.document_number} وتحديث المخزون والتكلفة.`);setLines([]);setInvoiceNo("");setDiscount("");setTax("")}catch(e){setMsg((e as Error).message)}finally{setSaving(false)}};
 return <main className="main"><div className="topbar"><div><h1 className="title">المشتريات</h1><div className="subtitle">Grid Entry — استلام المورد وتحديث المخزون والحسابات في عملية واحدة</div></div><div className="top-actions"><span className="badge blue"><Upload size={11}/> Excel / Paste</span><span className="badge green"><Truck size={11}/> Stock Receipt</span></div></div>
 <div className="split"><section className="card"><div className="panel-title"><span>بيانات المورد</span><select value={location?.id||""} onChange={e=>setLocation(locations.find(x=>x.id===e.target.value)||null)} style={{border:"1px solid #e2e8f0",borderRadius:7,padding:5,fontSize:9}}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>
 <div className="card" style={{padding:11,background:"#f8fafc",marginBottom:10}}><label className="metric-label">رقم فاتورة المورد<input className="field" value={invoiceNo} onChange={e=>setInvoiceNo(e.target.value)} placeholder="اختياري" style={{marginTop:6}} /></label><label className="metric-label" style={{display:"block",marginTop:10}}>المورد</label><select value={supplier?.id||""} onChange={e=>setSupplier(suppliers.find(x=>x.id===e.target.value)||null)} style={{width:"100%",marginTop:6,padding:9,border:"1px solid #e2e8f0",borderRadius:8,background:"#fff"}}><option value="">اختار المورد...</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name} — {s.code}</option>)}</select></div>
 <div className="panel-title">إضافة صنف</div><div className="card" style={{padding:10,background:"#f8fafc",display:"flex",gap:8,alignItems:"center"}}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الصنف / SKU / barcode..." style={{border:0,background:"transparent",outline:0,flex:1,fontSize:11}}/><Plus size={16}/></div>
 {q&&products.filter(p=>(p.name_ar+" "+p.sku).includes(q)).slice(0,8).map(p=><button key={p.id} onClick={()=>add(p)} style={{display:"flex",justifyContent:"space-between",width:"100%",border:0,borderBottom:"1px solid #eef2f7",background:"#fff",padding:"11px 5px",textAlign:"right"}}><span><strong>{p.name_ar}</strong><small style={{display:"block",color:"#64748b"}}>{p.sku}</small></span><span>{Number(p.default_cost||0).toLocaleString("ar-EG")} EGP</span></button>)}</section>
 <section className="card"><div className="panel-title"><span>بنود الفاتورة</span><span className="badge blue">{lines.length} أصناف</span></div>{lines.map((l,i)=><div key={l.product.id} style={{display:"grid",gridTemplateColumns:"1fr 70px 90px 75px",gap:8,alignItems:"center",padding:"11px 0",borderBottom:"1px solid #eef2f7"}}><span><strong style={{fontSize:10}}>{l.product.name_ar}</strong><small style={{display:"block",color:"#64748b",fontSize:8}}>{l.product.sku}</small></span><input type="number" min="1" value={l.quantity} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,quantity:Number(e.target.value)}:v))} style={{width:70,padding:6,border:"1px solid #e2e8f0",borderRadius:7}}/><input type="number" min="1" step="any" value={l.conversion_factor} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,conversion_factor:Math.max(0.000001,Number(e.target.value)||1)}:v))} style={{width:75,padding:6,border:"1px solid #e2e8f0",borderRadius:7}} placeholder="×" /><input type="number" min="0" step="0.01" value={l.unit_cost} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,unit_cost:Number(e.target.value)}:v))} style={{width:90,padding:6,border:"1px solid #e2e8f0",borderRadius:7}}/></div>)}{!lines.length&&<div style={{padding:"45px 10px",textAlign:"center",color:"#64748b",fontSize:11}}>أضف الأصناف واحدًا وراء الآخر أو جهّز لاحقًا للاستيراد الجماعي.</div>}
 <div className="form-grid" style={{marginTop:16}}><label>خصم<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} /></label><label>ضريبة<input type="number" min="0" step="0.01" value={tax} onChange={e=>setTax(e.target.value)} /></label></div><div style={{marginTop:18,paddingTop:14,borderTop:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between"}}><span>إجمالي التكلفة</span><strong style={{fontSize:22}}>{total.toLocaleString("ar-EG")} <small style={{fontSize:10}}>EGP</small></strong></div>{msg&&<div className="badge blue" style={{marginTop:10}}>{msg}</div>}<button className="primary" disabled={saving} onClick={post} style={{marginTop:12,display:"flex",justifyContent:"center",gap:8}}><ClipboardList size={16}/> {saving?"جاري الاستلام...":"استلام الفاتورة"}</button></section></div></main>
}