"use client";
import { useEffect,useState } from "react";
import { CircleDollarSign } from "lucide-react";
import { api } from "@/lib/api";
type Party={id:string;name:string;code:string};
type Ref={accounts:{id:string;name:string}[];payment_methods:{id:string;name_ar:string}[]};
export default function Payments(){const[customers,setCustomers]=useState<Party[]>([]),[suppliers,setSuppliers]=useState<Party[]>([]),[refs,setRefs]=useState<Ref>({accounts:[],payment_methods:[]}),[partyType,setPartyType]=useState<"customer"|"supplier">("customer"),[party,setParty]=useState(""),[account,setAccount]=useState(""),[method,setMethod]=useState(""),[amount,setAmount]=useState(""),[msg,setMsg]=useState("");
useEffect(()=>{api<Party[]>("/customers").then(setCustomers);api<Party[]>("/suppliers").then(setSuppliers);api<Ref>("/finance/references").then(x=>{setRefs(x);setAccount(x.accounts[0]?.id||"");setMethod(x.payment_methods[0]?.id||"")})},[]);
const submit=async()=>{if(!party||!account||!method||Number(amount)<=0)return setMsg("أكمل بيانات التحصيل.");try{await api("/payments",{method:"POST",body:JSON.stringify({party_type:partyType,party_id:party,financial_account_id:account,payment_method_id:method,direction:partyType==="customer"?"inbound":"outbound",amount:Number(amount),idempotency_key:crypto.randomUUID()})});setMsg("تم تسجيل العملية وتحديث الرصيد.");setAmount("")}catch(e){setMsg((e as Error).message)}};
const list=partyType==="customer"?customers:suppliers;return <main className="main"><div className="topbar"><div><h1 className="title">التحصيلات والمدفوعات</h1><div className="subtitle">Customer Collection / Supplier Payment</div></div><CircleDollarSign size={20}/></div><section className="card" style={{maxWidth:650}}><div className="form-grid"><label>النوع<select value={partyType} onChange={e=>{setPartyType(e.target.value as "customer"|"supplier");setParty("")}}><option value="customer">تحصيل من عميل</option><option value="supplier">دفع لمورد</option></select></label><label>الطرف<select value={party} onChange={e=>setParty(e.target.value)}><option value="">اختار...</option>{list.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select></label><label>الحساب المالي<select value={account} onChange={e=>setAccount(e.target.value)}>{refs.accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>طريقة الدفع<select value={method} onChange={e=>setMethod(e.target.value)}>{refs.payment_methods.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></label><label>المبلغ<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} /></label></div>{msg&&<div className="badge blue" style={{marginTop:12}}>{msg}</div>}<button className="primary" onClick={submit} style={{marginTop:12,width:"100%"}}>تسجيل العملية</button></section></main>}