"use client";
import { useEffect,useState } from "react";
import { Search, Plus, Trash2, ScanBarcode, CircleDollarSign } from "lucide-react";
import { api } from "@/lib/api";
type Product={id:string;sku:string;name_ar:string;default_piece_price:number;default_cost:number};
type Customer={id:string;code:string;name:string;phone?:string};
type Location={id:string;name:string;code:string};
type Line={product:Product;quantity:number;unit_price:number};
export default function Sales(){
 const [customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[locations,setLocations]=useState<Location[]>([]),[customer,setCustomer]=useState<Customer|null>(null),[location,setLocation]=useState<Location|null>(null),[lines,setLines]=useState<Line[]>([]),[q,setQ]=useState(""),[customerQ,setCustomerQ]=useState(""),[discount,setDiscount]=useState(""),[tax,setTax]=useState(""),[paid,setPaid]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{api<Customer[]>("/customers").then(setCustomers).catch(()=>{});api<Product[]>("/products").then(setProducts).catch(()=>{});api<Location[]>("/locations").then(x=>{setLocations(x);setLocation(x[0]||null)}).catch(()=>{})},[]);
 const add=(p:Product)=>{setLines(x=>{const e=x.find(v=>v.product.id===p.id);return e?x.map(v=>v.product.id===p.id?{...v,quantity:v.quantity+1}:v):[...x,{product:p,quantity:1,unit_price:Number(p.default_piece_price||0)}]});setQ("")};
 const subtotal=lines.reduce((s,l)=>s+l.quantity*l.unit_price,0); const total=Math.max(0,subtotal-Number(discount||0)+Number(tax||0)); const paidAmount=Math.min(Math.max(0,Number(paid||0)),total); const balanceDue=Math.max(0,total-paidAmount);
 const post=async()=>{if(!customer||!location||!lines.length)return setMessage("اختار العميل والموقع وأضف صنف واحد على الأقل.");if(total<=0)return setMessage("إجمالي الفاتورة لازم يكون أكبر من صفر.");setSaving(true);setMessage("");try{const r=await api<{document_number:string;total:string;balance_due:string}>("/sales",{method:"POST",body:JSON.stringify({customer_id:customer.id,location_id:location.id,discount:Number(discount||0),tax:Number(tax||0),paid_amount:paidAmount,idempotency_key:crypto.randomUUID(),items:lines.map(l=>({product_id:l.product.id,quantity:l.quantity,unit_price:l.unit_price}))})});setMessage(`تم تسجيل ${r.document_number} — الإجمالي ${Number(r.total).toLocaleString("ar-EG")} EGP — المتبقي ${Number(r.balance_due).toLocaleString("ar-EG")} EGP`);setLines([]);setDiscount("");setTax("");setPaid("")}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}};
 return <main className="main"><div className="topbar"><div><h1 className="title">بيع سريع</h1><div className="subtitle">Customer → Product → Quantity → Price → Payment → Post</div></div><span className="badge blue">Fast Sale</span></div>
 <div className="split"><section className="card"><div className="panel-title"><span>العميل</span><select value={location?.id||""} onChange={e=>setLocation(locations.find(x=>x.id===e.target.value)||null)} style={{border:"1px solid #e2e8f0",borderRadius:7,padding:5,fontSize:9}}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><input className="field" value={customerQ} onChange={e=>setCustomerQ(e.target.value)} placeholder="ابحث بالاسم أو الهاتف أو كود العميل..." />{customerQ&&<div style={{border:"1px solid #e2e8f0",borderRadius:8,overflow:"hidden"}}>{customers.filter(c=>(c.name+" "+(c.phone||"")+" "+c.code).toLowerCase().includes(customerQ.toLowerCase())).slice(0,8).map(c=><button key={c.id} onClick={()=>{setCustomer(c);setCustomerQ(c.name)}} style={{display:"flex",justifyContent:"space-between",width:"100%",border:0,borderBottom:"1px solid #eef2f7",background:"#fff",padding:10,textAlign:"right"}}><strong>{c.name}</strong><small>{c.phone||c.code}</small></button>)}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:8}}>{customers.slice(0,6).map(c=><button key={c.id} onClick={()=>setCustomer(c)} className="quick"><span><strong>{c.name}</strong><span>{c.phone||c.code}</span></span></button>)}</div>
 <div className="panel-title" style={{marginTop:20}}>إضافة صنف</div><div className="card" style={{padding:10,background:"#f8fafc",display:"flex",gap:8,alignItems:"center"}}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم الصنف / SKU / barcode..." style={{border:0,background:"transparent",outline:0,flex:1,fontSize:11}}/><ScanBarcode size={16}/></div>
 {q&&products.filter(p=>(p.name_ar+" "+p.sku).includes(q)).slice(0,8).map(p=><button key={p.id} onClick={()=>add(p)} style={{display:"flex",justifyContent:"space-between",width:"100%",border:0,borderBottom:"1px solid #eef2f7",background:"#fff",padding:"11px 5px",textAlign:"right"}}><span><strong>{p.name_ar}</strong><small style={{display:"block",color:"#64748b"}}>{p.sku}</small></span><span>{Number(p.default_piece_price||0).toLocaleString("ar-EG")} EGP</span></button>)}</section>
 <section className="card"><div className="panel-title"><span>تفاصيل الفاتورة</span><span className="badge blue">{lines.length} أصناف</span></div>{lines.map((l,i)=><div key={l.product.id} style={{display:"grid",gridTemplateColumns:"1fr 70px 90px 28px",gap:8,alignItems:"center",padding:"11px 0",borderBottom:"1px solid #eef2f7"}}><span><strong style={{fontSize:10}}>{l.product.name_ar}</strong><small style={{display:"block",color:"#64748b",fontSize:8}}>{l.product.sku}</small></span><input type="number" min="1" value={l.quantity} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,quantity:Number(e.target.value)}:v))} style={{width:70,padding:6,border:"1px solid #e2e8f0",borderRadius:7}}/><span style={{fontSize:10}}>{(l.quantity*l.unit_price).toLocaleString("ar-EG")} EGP</span><button onClick={()=>setLines(x=>x.filter(v=>v.product.id!==l.product.id))} className="icon-btn"><Trash2 size={13}/></button></div>)}{!lines.length&&<div style={{padding:"45px 10px",textAlign:"center",color:"#64748b",fontSize:11}}>ابدأ بإضافة المنتجات — بدون فتح شاشات إضافية.</div>}
 <div style={{marginTop:18,paddingTop:14,borderTop:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontWeight:700}}>الإجمالي</span><strong style={{fontSize:22}}>{total.toLocaleString("ar-EG")} <small style={{fontSize:10}}>EGP</small></strong></div>
 <div className="form-grid" style={{marginTop:16}}><label>خصم<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} /></label><label>ضريبة<input type="number" min="0" step="0.01" value={tax} onChange={e=>setTax(e.target.value)} /></label><label>المدفوع الآن<input type="number" min="0" step="0.01" value={paid} onChange={e=>setPaid(e.target.value)} placeholder="0 = آجل" /></label></div><div style={{marginTop:18,paddingTop:14,borderTop:"1px solid #e2e8f0",display:"grid",gap:7}}><div style={{display:"flex",justifyContent:"space-between"}}><span>الإجمالي</span><strong style={{fontSize:22}}>{total.toLocaleString("ar-EG")} <small style={{fontSize:10}}>EGP</small></strong></div><div style={{display:"flex",justifyContent:"space-between"}}><span>المدفوع</span><strong>{paidAmount.toLocaleString("ar-EG")} EGP</strong></div><div style={{display:"flex",justifyContent:"space-between"}}><span>الرصيد المتبقي</span><strong>{balanceDue.toLocaleString("ar-EG")} EGP</strong></div></div>{message&&<div className="badge blue" style={{marginTop:10,padding:9}}>{message}</div>}<button className="primary" disabled={saving} onClick={post} style={{marginTop:12,display:"flex",justifyContent:"center",gap:8}}><CircleDollarSign size={16}/>{saving?"جاري تسجيل البيع...":"تسجيل البيع"}</button></section></div></main>
}