"use client";
import { useEffect,useState } from "react";
import { RotateCcw, Search, PackageCheck } from "lucide-react";
import { api } from "@/lib/api";
type Party={id:string;name:string;code:string};type Product={id:string;sku:string;name_ar:string;default_piece_price:number;default_cost:number};type Location={id:string;name:string;code:string};type Line={product:Product;quantity:number;unit_price:number};
export default function Returns(){
 const [customers,setCustomers]=useState<Party[]>([]),[products,setProducts]=useState<Product[]>([]),[locations,setLocations]=useState<Location[]>([]),[customer,setCustomer]=useState(""),[location,setLocation]=useState(""),[q,setQ]=useState(""),[lines,setLines]=useState<Line[]>([]),[msg,setMsg]=useState("");
 useEffect(()=>{api<Party[]>("/customers").then(setCustomers).catch(()=>{});api<Product[]>("/products").then(setProducts).catch(()=>{});api<Location[]>("/locations").then(x=>{setLocations(x);setLocation(x[0]?.id||"")}).catch(()=>{})},[]);
 const add=(p:Product)=>{setLines(x=>x.some(l=>l.product.id===p.id)?x.map(l=>l.product.id===p.id?{...l,quantity:l.quantity+1}:l):[...x,{product:p,quantity:1,unit_price:Number(p.default_piece_price||0)}]);setQ("")};
 const total=lines.reduce((s,l)=>s+l.quantity*l.unit_price,0);
 const post=async()=>{if(!customer||!location||!lines.length)return setMsg("اختار العميل والموقع وأضف الأصناف المرتجعة.");try{await api("/returns/sales",{method:"POST",body:JSON.stringify({customer_id:customer,location_id:location,idempotency_key:crypto.randomUUID(),items:lines.map(l=>({product_id:l.product.id,quantity:l.quantity,unit_price:l.unit_price}))})});setMsg("تم تسجيل مرتجع المبيعات وإعادة الكمية للمخزون.");setLines([])}catch(e){setMsg((e as Error).message)}};
 return <main className="main"><div className="topbar"><div><h1 className="title">المرتجعات</h1><div className="subtitle">Sales Return — إعادة المخزون وتعديل حساب العميل داخل Transaction واحدة</div></div><span className="badge amber"><RotateCcw size={11}/> Return</span></div>
 <section className="card"><div className="form-grid"><label>العميل<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">اختار العميل...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.code}</option>)}</select></label><label>الموقع<select value={location} onChange={e=>setLocation(e.target.value)}>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div>
 <div className="panel-title" style={{marginTop:18}}>الصنف المرتجع</div><div className="card" style={{padding:10,background:"#f8fafc",display:"flex",gap:8}}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن الصنف..." style={{border:0,background:"transparent",outline:0,flex:1}}/></div>{q&&products.filter(p=>(p.name_ar+" "+p.sku).includes(q)).slice(0,8).map(p=><button key={p.id} onClick={()=>add(p)} style={{display:"flex",justifyContent:"space-between",width:"100%",border:0,borderBottom:"1px solid #eef2f7",background:"#fff",padding:"10px",textAlign:"right"}}><span>{p.name_ar}<small style={{display:"block",color:"#64748b"}}>{p.sku}</small></span><span>{Number(p.default_piece_price||0).toLocaleString("ar-EG")} EGP</span></button>)}
 <div style={{marginTop:12}}>{lines.map((l,i)=><div key={l.product.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:"1px solid #eef2f7"}}><span>{l.product.name_ar}</span><input type="number" min="1" value={l.quantity} onChange={e=>setLines(x=>x.map((v,j)=>j===i?{...v,quantity:Number(e.target.value)}:v))} style={{width:75,padding:7,border:"1px solid #e2e8f0",borderRadius:7}}/></div>)}</div>
 <div style={{display:"flex",justifyContent:"space-between",marginTop:15}}><span>قيمة المرتجع</span><strong>{total.toLocaleString("ar-EG")} EGP</strong></div>{msg&&<div className="badge blue" style={{marginTop:10}}>{msg}</div>}<button className="primary" onClick={post} style={{marginTop:12,display:"flex",justifyContent:"center",gap:8}}><PackageCheck size={16}/> تسجيل المرتجع</button></section></main>
}