"use client";
import { useEffect,useState } from "react";
import { MapPin, Navigation, Phone, RefreshCw, Wifi, WifiOff } from "lucide-react";
import { api } from "@/lib/api";
import FieldActions from "./FieldActions";
type Customer={id:string;name:string;code:string;phone?:string;address_text?:string;latitude?:number;longitude?:number;sequence:number;visit_status:string};
type Product={id:string;sku:string;name_ar:string;quantity_base:number};
type Trip={id:string;trip_number:string;status:string;vehicle_name:string;vehicle_code:string;vehicle_location_id:string};
export default function Field(){
 const [trip,setTrip]=useState<Trip|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[stock,setStock]=useState<Product[]>([]),[online,setOnline]=useState(true),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 const load=()=>{setLoading(true);api<{trip:Trip|null;customers:Customer[];stock:Product[]}>("/field/today").then(x=>{setTrip(x.trip);setCustomers(x.customers);setStock(x.stock)}).catch(e=>setMsg(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);load();return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
 const visit=async(c:Customer,status:"checked_in"|"visited")=>{try{await apiWithOfflineQueue("/field/visits",{method:"POST",body:JSON.stringify({trip_id:trip?.id,customer_id:c.id,status})});setCustomers(x=>x.map(v=>v.id===c.id?{...v,visit_status:status}:v));setMsg(online?"تم تحديث الزيارة":"تم حفظ الزيارة محليًا وسيتم إرسالها عند عودة الإنترنت.")}catch(e){setMsg((e as Error).message)}};
 const locate=()=>navigator.geolocation?.getCurrentPosition(p=>setMsg("الموقع الحالي: "+p.coords.latitude.toFixed(5)+", "+p.coords.longitude.toFixed(5)),()=>setMsg("تعذر الحصول على الموقع."));
 return <main className="field-main"><header className="field-header"><div><div className="brand-mini">NEXORA</div><h1>رحلة اليوم</h1><span>{trip?trip.trip_number+" · "+trip.vehicle_name:"لا توجد رحلة اليوم"}</span></div><div style={{display:"flex",gap:7}}><span className={"connection "+(online?"":"offline")}>{online?<Wifi size={13}/>:<WifiOff size={13}/>} {online?"متصل":"Offline"}</span><button className="icon-btn" onClick={load}><RefreshCw size={15}/></button></div></header>
 <div className="field-stats"><div><strong>{customers.length}</strong><span>عملاء</span></div><div><strong>{customers.filter(c=>c.visit_status==="visited").length}</strong><span>تمت زيارتهم</span></div><div><strong>{stock.length}</strong><span>أصناف</span></div></div>
 <section className="field-card"><div className="field-card-title"><span>العملاء</span><button className="secondary" onClick={locate}><MapPin size={13}/> موقعي</button></div>{loading?<p>جاري تحميل الرحلة...</p>:customers.map(c=><article className="customer-stop" key={c.id}><div className="stop-main"><span className="stop-number">{c.sequence}</span><div><strong>{c.name}</strong><small>{c.phone||c.code}</small><small>{c.address_text||"بدون عنوان"}</small></div></div><div className="stop-actions"><button onClick={()=>visit(c,"checked_in")} className="visit-check">وصول</button><button onClick={()=>visit(c,"visited")} className="visit-done">تمت</button>{c.phone&&<a href={"tel:"+c.phone} className="icon-btn"><Phone size={14}/></a>}{c.latitude&&c.longitude&&<a target="_blank" rel="noreferrer" href={"https://www.google.com/maps/dir/?api=1&destination="+c.latitude+","+c.longitude} className="icon-btn"><Navigation size={14}/></a>}</div></article>)}</section>
 <section className="field-card"><div className="field-card-title"><span>مخزون العربية</span><span className="badge blue">{stock.length} صنف</span></div><div className="field-products">{stock.slice(0,40).map(p=><div key={p.id}><span>{p.name_ar}<small>{p.sku}</small></span><strong>{Number(p.quantity_base).toLocaleString("ar-EG")}</strong></div>)}</div></section>
 {msg&&<div className="field-toast">{msg}</div>}{trip&&customers.filter(c=>c.visit_status==="checked_in").map(c=><FieldActions key={c.id} trip={trip} customer={c} stock={stock} onDone={()=>{setMsg("تم تنفيذ العملية.");load()}}/> )}</main>
}