"use client";
import { useEffect,useState } from "react";
import { Search, Users, Plus, X } from "lucide-react";
import { api } from "@/lib/api";
type Supplier={id:string;name:string;code:string;phone?:string;tax_identifier?:string;tax_number?:string;address?:string;address_text?:string;status:string};
type Form={name:string;code:string;phone:string;tax_number:string;address_text:string};
const blank:Form={name:"",code:"",phone:"",tax_number:"",address_text:""};
export default function Suppliers(){
 const[rows,setRows]=useState<Supplier[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[form,setForm]=useState<Form>(blank);
 const load=()=>{setLoading(true);return api<Supplier[]>("/suppliers?q="+encodeURIComponent(q)).then(setRows).catch(e=>setMsg(e.message)).finally(()=>setLoading(false))};
 useEffect(()=>{const t=setTimeout(()=>{void load()},200);return()=>clearTimeout(t)},[q]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setMsg("");try{await api<Supplier>("/suppliers",{method:"POST",body:JSON.stringify({...form,code:form.code||null,phone:form.phone||null,tax_number:form.tax_number||null,address_text:form.address_text||null})});setMsg("تمت إضافة المورد بنجاح.");setOpen(false);setForm(blank);await load()}catch(e){setMsg((e as Error).message)}finally{setSaving(false)}};
 return <main className="main"><div className="topbar"><div><h1 className="title">الموردين</h1><div className="subtitle">Suppliers — المصدر والحسابات الدائنة</div></div><button className="primary" onClick={()=>{setMsg("");setOpen(true)}} style={{width:"auto",padding:"10px 15px",display:"flex",gap:7,alignItems:"center"}}><Plus size={15}/> مورد جديد</button></div>
 <div className="card" style={{marginBottom:12,display:"flex",gap:8,alignItems:"center"}}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو الكود أو الهاتف..." style={{border:0,outline:0,flex:1}}/></div>{msg&&!open&&<div className="badge blue" style={{padding:10,marginBottom:10}}>{msg}</div>}
 <div className="table-wrap"><table><thead><tr><th>المورد</th><th>الكود</th><th>الهاتف</th><th>الرقم الضريبي</th><th>الحالة</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>جاري التحميل...</td></tr>:rows.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.code}</td><td>{s.phone||"—"}</td><td>{s.tax_identifier||s.tax_number||"—"}</td><td><span className="badge green">نشط</span></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={5}>لا يوجد موردون مطابقون للبحث.</td></tr>}</tbody></table></div>
 {open&&<div style={{position:"fixed",inset:0,background:"#0b173080",display:"grid",placeItems:"center",zIndex:50,padding:18}}><form className="card" onSubmit={save} style={{width:"min(680px,100%)",maxHeight:"90vh",overflow:"auto"}}><div className="panel-title"><span style={{fontSize:15}}>إضافة مورد جديد</span><button type="button" className="icon-btn" onClick={()=>setOpen(false)}><X size={14}/></button></div><div className="form-grid">
 <label>اسم المورد *<input required maxLength={255} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الكود<input maxLength={64} value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="يتولد تلقائيًا"/></label><label>رقم الهاتف<input maxLength={32} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>الرقم الضريبي<input maxLength={128} value={form.tax_number} onChange={e=>setForm({...form,tax_number:e.target.value})}/></label><label style={{gridColumn:"1 / -1"}}>العنوان<input value={form.address_text} onChange={e=>setForm({...form,address_text:e.target.value})}/></label>
 </div>{msg&&<div style={{marginTop:10}} className="badge blue">{msg}</div>}<div style={{display:"flex",gap:8,marginTop:14,justifyContent:"flex-end"}}><button type="button" className="icon-btn" onClick={()=>setOpen(false)}>إلغاء</button><button className="primary" disabled={saving}>{saving?"جاري الحفظ...":"حفظ المورد"}</button></div></form></div>}
 </main>
}
