"use client";
import { useEffect,useState } from "react";
import { CircleDollarSign, Search, WalletCards, Building2 } from "lucide-react";
import { api } from "@/lib/api";
type Party={id:string;name:string;code:string;phone?:string};
type Ref={accounts:{id:string;name:string;code:string}[];payment_methods:{id:string;name_ar:string;code:string;requires_reference:boolean}[]};
export default function Collections(){
 const [customers,setCustomers]=useState<Party[]>([]),[suppliers,setSuppliers]=useState<Party[]>([]),[ref,setRef]=useState<Ref>({accounts:[],payment_methods:[]}),[partyType,setPartyType]=useState<"customer"|"supplier">("customer"),[party,setParty]=useState(""),[account,setAccount]=useState(""),[method,setMethod]=useState(""),[amount,setAmount]=useState(""),[reference,setReference]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{api<Party[]>("/customers").then(setCustomers).catch(()=>{});api<Party[]>("/suppliers").then(setSuppliers).catch(()=>{});api<Ref>("/finance/references").then(x=>{setRef(x);setAccount(x.accounts[0]?.id||"");setMethod(x.payment_methods[0]?.id||"")}).catch(()=>{})},[]);
 const parties=partyType==="customer"?customers:suppliers;
 const submit=async()=>{const pm=ref.payment_methods.find(x=>x.id===method);if(!party||!account||!method||Number(amount)<=0)return setMsg("اختار الطرف والحساب وطريقة الدفع وأدخل مبلغ صحيح.");if(pm?.requires_reference&&!reference)return setMsg("طريقة الدفع دي محتاجة رقم مرجعي.");try{await api("/payments",{method:"POST",body:JSON.stringify({party_type:partyType,party_id:party,financial_account_id:account,payment_method_id:method,direction:partyType==="customer"?"inbound":"outbound",amount:Number(amount),reference,idempotency_key:crypto.randomUUID()})});setMsg("تم تسجيل العملية وتحديث الحساب.");setAmount("");setReference("")}catch(e){setMsg((e as Error).message)}};
 return <main className="main"><div className="topbar"><div><h1 className="title">التحصيلات والحسابات</h1><div className="subtitle">Customer / Supplier → Payment Method → Account → Ledger</div></div><span className="badge green">Financial Posting</span></div>
 <div className="grid" style={{marginBottom:14}}>{([["تحصيل عميل","Inbound",WalletCards],["سداد مورد","Outbound",Building2],["مرجع الدفع","Bank / Postal",CircleDollarSign]] as [string,string,import("lucide-react").LucideIcon][]).map(([a,b,I])=><div className="card metric" key={String(a)}><div className="metric-top"><span className="metric-label">{a}</span><span className="metric-icon"><I size={15}/></span></div><div className="metric-value" style={{fontSize:16}}>{b}</div></div>)}</div>
 <section className="card" style={{maxWidth:900}}><div className="panel-title">تسجيل حركة مالية</div>
 <div className="segmented"><button className={partyType==="customer"?"selected":""} onClick={()=>{setPartyType("customer");setParty("")}}>تحصيل من عميل</button><button className={partyType==="supplier"?"selected":""} onClick={()=>{setPartyType("supplier");setParty("")}}>سداد لمورد</button></div>
 <div className="form-grid"><label>الطرف<select value={party} onChange={e=>setParty(e.target.value)}><option value="">اختار...</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name} — {p.code}</option>)}</select></label><label>الحساب المالي<select value={account} onChange={e=>setAccount(e.target.value)}><option value="">اختار...</option>{ref.accounts.map(a=><option key={a.id} value={a.id}>{a.name} — {a.code}</option>)}</select></label><label>طريقة الدفع<select value={method} onChange={e=>setMethod(e.target.value)}><option value="">اختار...</option>{ref.payment_methods.map(m=><option key={m.id} value={m.id}>{m.name_ar}</option>)}</select></label><label>المبلغ<input type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label>المرجع<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="رقم التحويل / الشيك..." /></label></div>
 {msg&&<div className="badge blue" style={{marginTop:12}}>{msg}</div>}<button className="primary" onClick={submit} style={{marginTop:14,display:"flex",justifyContent:"center",gap:8}}><CircleDollarSign size={16}/> تسجيل الحركة</button></section></main>
}